### ISSUE TITLE
zio-app dev won't launch - dist/index.html not found

### ISSUE THREAD

**Issue by softdevca** [kitlangton/zio-app#18]
`zio-app dev` starts but when the link is opened an exception results because `dist/index.html` is not on the classpath. 

`zio-app` is built from the latest source as of 2021-06-16.

```
sheldon@blackbird:~/code/scratch/newapp$ zio-app dev
Running Dev Mode     
http://localhost:9630
STARTING SERVER ON PORT 9630
Jun 16, 2021 10:30:23 AM io.netty.channel.DefaultChannelPipeline onUnhandledInboundException
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.FileNotFoundException: resource 'dist/index.html' was not found in the classpath from the given classloader.
	at scala.io.Source$.fromResource(Source.scala:183)
	at zio.app.Backend$$anonfun$app$1.applyOrElse(Backend.scala:57)
	at zio.app.Backend$$anonfun$app$1.applyOrElse(Backend.scala:43)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
	at zhttp.http.Http.execute(Http.scala:181)
	at zhttp.http.Http.execute$(Http.scala:174)
	at zhttp.http.Http$Collect.execute(Http.scala:197)
	at zhttp.service.server.ServerRequestHandler.executeAsync(ServerRequestHandler.scala:38)
	at zhttp.service.server.ServerRequestHandler.channelRead0(ServerRequestHandler.scala:62)
	at zhttp.service.server.ServerRequestHandler.channelRead0(ServerRequestHandler.scala:16)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.HttpServerKeepAliveHandler.channelRead(HttpServerKeepAliveHandler.java:64)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
```

**Comment by kitlangton** [comment]
Ah, I must upgrade the instructions even more :P 
Try running `./release.sh`, this will put the `dist/index.html` in the right place.

**Comment by softdevca** [comment]
Is there a way to modify the build process so the step isn't necessary
instead?  The only thing better than documentation is not needing
documentation. :)

I haven't run `release.sh` yet but I suspect something is amiss with this
line:

```
mv ./cli-frotnend/dist ./cli/src/main/resources/dist
```

**Comment by kitlangton** [comment]
😆 Yeah. `frotnend`... doh.

**Comment by kitlangton** [comment]
I'm not sure. I'd have to see if I can make an `sbt` command that will basically do what that script does. Good idea though.

**Comment by mtjon** [comment]
I encountered the same issue as OP, but looking at `release.sh` I see several issues that may need to be addressed:
- `frotnend` as mentioned above
- still need to run `yarn install` from `cli-frontend` (or ensure that it has been run)
- the `mv ./cli-frontend/dist ./cli/src/main/resources/dist` fails as the dir does not exist:
  - but looking at `cli-frontend/vite.config.js` this line: `outDir: '../cli/src/main/resources/dist',` should take care of that already.
- `open .` is a macOS command

I did get the `zio-app dev` to run after taking care of this.

**Comment by mtjon** [comment]
> 
> 
> I'm not sure. I'd have to see if I can make an `sbt` command that will basically do what that script does. Good idea though.

We could perhaps make use of sbt's support for [external processes](https://www.scala-sbt.org/1.x/docs/Process.html#External+Processes) to run the `yarn exec -- vite build`, and 
```
tar -czf zio-app.gz zio-app
echo $(shasum -a 256 zio-app.gz)
```

Using the [`nativeImageOutput` configuration](https://www.scala-sbt.org/1.x/docs/Process.html) should help us get rid of 
```sh
cd cli/target/native-image
mv zio-app-cli zio-app
```
altogether.

And wrap it all up into a custom sbt task.

**Comment by kitlangton** [comment]
Thanks for exploring this @mtjon! I'll look into wrapping this into an sbt task :)
