### ISSUE TITLE
[linux][bug] DirectoryNotEmptyException

### ISSUE THREAD

**Issue by fokot** [kitlangton/zio-app#21]
Every time I try to create new project I get
```
Configure your new ZIO app.
? Project Name (example) terremoto 
Fiber failed.
A checked error was not handled.
java.nio.file.DirectoryNotEmptyException: /tmp/zio-app-g85522636012018003419/zio-app/cli/src/main/g8
	at sun.nio.fs.UnixCopyFile.ensureEmptyDir(UnixCopyFile.java:384)
	at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:484)
	at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:267)
	at java.nio.file.Files.move(Files.java:1421)
	at zio.nio.file.Files$.$anonfun$move$1(Files.scala:144)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:490)
	at zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:776)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)

Fiber:Id(1628020033759,1) was supposed to continue to:
  a future continuation at <couldn't get location, error: couldn't find class file for lambda:zio.app.TemplateGenerator$$$Lambda$bb2df6d5e62bb4ba6c73f539d6631044adae49ac@7f77e3e27d30>
  a future continuation at <couldn't get location, error: couldn't find class file for lambda:zio.app.Main$$$Lambda$7778727ad602439cf3fea3b18022da5c909f5755@5591800a4a20>
  a future continuation at <couldn't get location, error: couldn't find class file for lambda:zio.ZIO$$Lambda$45021940fc96b17e50c19451b35690adf43cd8ce@5591800a4ad8>

Fiber:Id(1628020033759,1) execution trace:
  at <couldn't get location, error: couldn't find class file for lambda:zio.ZIO$$Lambda$87ee315aec2f118e1ff9b6a17a0f6546c59caf18@7f77e3e17270>
  at <couldn't get location, error: couldn't find class file for lambda:zio.ZIO$$$Lambda$9e2b450b58bae2e34ea9003a32facdd160484e7d@7f77e2a012e0>
  at <couldn't get location, error: couldn't find class file for lambda:zio.ZIO$$$Lambda$08f75e6ea39cbf1b97df8667068bd09c189cccdb@7f77e2a0fa38>
  at <couldn't get location, error: couldn't find class file for lambda:zio.internal.FiberContext$$Lambda$79cdd98a42b76d405891ede6d4bc3b44af9790a9@5591800a5240>
  at <couldn't get location, error: couldn't find class file for lambda:zio.internal.FiberContext$$Lambda$dc15ed66617f3c632f31ac45c64d3eaf307af4cf@7f77e340aea0>
  at <couldn't get location, error: couldn't find class file for lambda:zio.ZIO$$$Lambda$9e2b450b58bae2e34ea9003a32facdd160484e7d@7f77e2a012e0>
  at <couldn't get location, error: couldn't find class file for lambda:zio.ZIO$$Lambda$1e801978cac787dbd1b4e9cf92c75e8385021c34@7f77e3408f28>
  at <couldn't get location, error: couldn't find class file for lambda:zio.ZIO$$Lambda$8335b74ac03fc772b8cdfc57c441c04a41ebc006@5591800a35b8>
  at <couldn't get location, error: couldn't find class file for lambda:zio.nio.file.Files$$$Lambda$e6fd550ab5b0784d95aaac4f6e6c817d9ca70544@7f77e3e27c00>
  at <couldn't get location, error: couldn't find class file for lambda:zio.ZIO$$$Lambda$9e2b450b58bae2e34ea9003a32facdd160484e7d@7f77e2a012e0>
  at <couldn't get location, error: couldn't find class file for lambda:zio.ZIO$$Lambda$275206b21901e3b6a12c4b9e9a0cd33ffffddc30@7f77e3408ee8>
  at <couldn't get location, error: couldn't find class file for lambda:zio.internal.FiberContext$$Lambda$79cdd98a42b76d405891ede6d4bc3b44af9790a9@5591800a5240>
  at <couldn't get location, error: couldn't find class file for lambda:zio.internal.FiberContext$$Lambda$dc15ed66617f3c632f31ac45c64d3eaf307af4cf@7f77e340aea0>
  at <couldn't get location, error: couldn't find class file for lambda:zio.ZIO$$$Lambda$5ed766280e50fccf0555411300784e9b512fb037@7f77e3406f80>
  at <couldn't get location, error: couldn't find class file for lambda:zio.blocking.package$$$Lambda$5dc8b1224f3a7bd1c0758716a1ad7df31aa8de53@7f77e3e0d5b0>
  at <couldn't get location, error: couldn't find class file for lambda:zio.app.TemplateGenerator$$$Lambda$e91e24703eab2fcd416743c60c2b87263543e1f2@7f77e3e25140>
  at <couldn't get location, error: couldn't find class file for lambda:zio.ZIO$ZipLeftFn$$Lambda$fdda0d509ce6db696778424dc566a41d5e6291ea@7f77e0201410>
  at <couldn't get location, error: couldn't find class file for lambda:zio.ZIO$$$Lambda$9e2b450b58bae2e34ea9003a32facdd160484e7d@7f77e2a012e0>
  at <couldn't get location, error: couldn't find class file for lambda:zio.Fiber$$Lambda$002ddf696bcc04daf47aa7ef79499356bef30f8f@7f77f09873d8>
  at <couldn't get location, error: couldn't find class file for lambda:zio.ZIO$$$Lambda$9e2b450b58bae2e34ea9003a32facdd160484e7d@7f77e2a012e0>
  at <couldn't get location, error: couldn't find class file for lambda:zio.Fiber$$Lambda$e8dc4bc55ea72e41b0343bee50775df59c9a60a8@5591800a3618>
  at <couldn't get location, error: couldn't find class file for lambda:zio.internal.FiberContext$InterruptExit$$$Lambda$38f3ba2734b1cfd6743e3cfb7fe28ea6e19c9186@7f77e2001328>
  at <couldn't get location, error: couldn't find class file for lambda:<function1>>
  at <couldn't get location, error: couldn't find class file for lambda:zio.ZIO$$Lambda$708699a2a4ba909fe7cd4c59898a03a18e869064@5591800a8d90>
  at <couldn't get location, error: couldn't find class file for lambda:<function1>>
  at <couldn't get location, error: couldn't find class file for lambda:zio.ZIO$$$Lambda$6ebd00c119348a9b417e02306ebcd20d803e5e6b@5591800a3ab8>
  at <couldn't get location, error: couldn't find class file for lambda:zio.internal.FiberContext$$Lambda$5310cd13f0a4a9131f429dcf5f75a46583f8cd57@7f77f0987320>
  at <couldn't get location, error: couldn't find class file for lambda:zio.ZIO$$$Lambda$fcf2f750fb0ff4851b8d380258696bdacdb83e1f@7f77f09872f8>
  at <couldn't get location, error: couldn't find class file for lambda:zio.ZIO$$$Lambda$d283822bba57a9b19d05e2b5bff7bfc40e09e7d2@5591800a3668>
  at <couldn't get location, error: couldn't find class file for lambda:zio.app.TemplateGenerator$$$Lambda$1f489afee0e74cc18710da4f5e5666ca55652cea@7f77e3e1b198>
  at <couldn't get location, error: couldn't find class file for lambda:zio.app.TemplateGenerator$$$Lambda$65bf70f1b5b65f5e7bb2f6987af545812f620065@5591800a4e28>
  at <couldn't get location, error: couldn't find class file for lambda:zio.ZIO$$Lambda$d09fc01d4810568de286f745acc718dd95748fcd@7f77e3e1b150>
  at <couldn't get location, error: couldn't find class file for lambda:zio.ZIO$$Lambda$87ee315aec2f118e1ff9b6a17a0f6546c59caf18@7f77e3e17270>
  at <couldn't get location, error: couldn't find class file for lambda:zio.console.package$Console$Service$$anon$1$$Lambda$141bd0d46bf33d8e428d3814ec15e39b51f262ec@5591800a5080>
  at <couldn't get location, error: couldn't find class file for lambda:zio.console.package$$$Lambda$933f2a0f5087470702c0c54c131856d09cd57494@5591800a4ff8>
  at <couldn't get location, error: couldn't find class file for lambda:zio.app.TemplateGenerator$$$Lambda$2de552e6de0deb7c100c6ebdfd3b2658d609a9a0@7f77e3e13150>
  at <couldn't get location, error: couldn't find class file for lambda:zio.ZIO$$Lambda$87ee315aec2f118e1ff9b6a17a0f6546c59caf18@7f77e3e17270>
  at <couldn't get location, error: couldn't find class file for lambda:zio.console.package$Console$Service$$$Lambda$6dedfd951c044b77e7d30a29bb8c60a4bc8d6206@7f77e3e171d8>
  at <couldn't get location, error: couldn't find class file for lambda:zio.console.package$$$Lambda$60e051406f8a15954d631dcb7948db9984035e96@7f77e3e13130>
  at <couldn't get location, error: couldn't find class file for lambda:zio.app.TemplateGenerator$$$Lambda$9e2e5b52dd334225ef20e10c3050fe8eb904ea9e@5591800a4e70>
  at <couldn't get location, error: couldn't find class file for lambda:zio.app.Main$$$Lambda$0b2653dfd65eb573498f55043080178d3fc8fe1d@5591800a4aa0>
  at <couldn't get location, error: couldn't find class file for lambda:zio.app.Main$$$Lambda$749df01be457e01fd56a77cdf64046647a785a35@7f77f0955460>

Fiber:Id(1628020033759,1) was spawned by:

Fiber:Id(1628020033759,0) was supposed to continue to:
  a future continuation at <couldn't get location, error: couldn't find class file for lambda:zio.App$$Lambda$0687f159aaebf867b07deb2dc4f87b776a50852c@7f77f097c708>
  a future continuation at <couldn't get location, error: couldn't find class file for lambda:zio.App$$Lambda$410106e1fd120c8af1933436050da4c64d5897b8@7f77f096f6e0>

Fiber:Id(1628020033759,0) ZIO Execution trace: <empty trace>

Fiber:Id(1628020033759,0) was spawned by: <empty trace>
```
Even if I delete directory before running the command.

I'm on commit 2e55fbbd659265eed0a8686bcd0042c5eab95ca3

**Comment by fokot** [comment]
Fixed by #24
