### ISSUE TITLE
zio-app dev hangs with no output

### ISSUE THREAD

**Issue by SimunKaracic** [kitlangton/zio-app#30]
Running the app manually using the steps described here works fine https://github.com/kitlangton/zio-hackathon

But running using `zio-app dev` open a browser window for the BE and FE output (which are always empty), and the console shows only this before hanging:
```
simunkaracic$ zio-app dev
Running Dev Mode
http://localhost:9630
STARTING SERVER ON PORT 9630
```

Running on mac OS, installed using `brew`. Please let me know if I can provide any additional details that would help with solving this issue

**Comment by dag2ww** [comment]
I just tried it (also installed via brew on MAC OS) and have the same results - empty panes of Backend and Frontend and frontend giving nothing. 

zio-app dev
Running Dev Mode     
http://localhost:9630
STARTING SERVER ON PORT 9630

**Comment by SimunKaracic** [comment]
After updating to the newest version, I get an error 🎉 
```
STARTING SERVER ON PORT 9630
Server started on port: 9630
Mar 11, 2022 5:05:49 PM io.netty.channel.DefaultChannelPipeline onUnhandledInboundException
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.FileNotFoundException: resource 'dist/index.html' was not found in the classpath from the given classloader.
        at scala.io.Source$.fromResource(Source.scala:183)
        at zio.app.Backend$$anonfun$app$1.applyOrElse(Backend.scala:57)
        at zio.app.Backend$$anonfun$app$1.applyOrElse(Backend.scala:38)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
        at zhttp.http.Http$PartialCollectZIO$$anonfun$apply$extension$1.applyOrElse(Http.scala:637)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
        at zhttp.http.Http.execute(Http.scala:388)
        at zhttp.http.Http.execute$(Http.scala:381)
        at zhttp.http.Http$Collect.execute(Http.scala:691)
        at zhttp.http.Http.execute(Http.scala:399)
        at zhttp.http.Http.execute$(Http.scala:381)
        at zhttp.http.Http$FoldHttp.execute(Http.scala:696)
        at zhttp.service.Handler.unsafeRun(Handler.scala:56)
        at zhttp.service.Handler.channelRead0(Handler.scala:26)
        at zhttp.service.Handler.channelRead0(Handler.scala:14)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:200)
        at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:162)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
        at io.netty.handler.codec.http.HttpServerKeepAliveHandler.channelRead(HttpServerKeepAliveHandler.java:64)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
```
