### ISSUE TITLE
build failure using cli/nativeImage

### ISSUE THREAD

**Issue by dacr** [kitlangton/zio-app#38]
While trying to build sbt-app v0.4.6 using linux host (linux mint 21) 
```
$ sbt cli/nativeImage
...
[/home/dcr/dev-third-parties/zio-app/cli/target/native-image/zio-app-cli:8472]    cla
[failure.log](https://github.com/kitlangton/zio-app/files/9846157/failure.log)
sslist:  10,336.73 ms,  1.09 GB
Error: Main entry point class 'zio.app.Main' not found.
com.oracle.svm.core.util.UserError$UserException: Main entry point class 'zio.app.Main' not found.
        at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:292)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:508)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:114)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:537)
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1558)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1308)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1269)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1228)
	at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1740)
[error] native-image command failed with exit code '1'
[error] (cli / nativeImage) native-image command failed with exit code '1'
[error] Total time: 34 s, completed 23 oct. 2022, 11:38:44
```

**Comment by dacr** [comment]
[failure.log](https://github.com/kitlangton/zio-app/files/9846160/failure.log)

**Comment by Reeebuuk** [comment]
Having the same issue. Brew version is quite old and using ZIO1 so a no go.
Can we get this resolved?
